#include <cstdlib>
#include <iostream>
#include <vector>
#include <string>
#include <time.h>
#include <windows.h>
using namespace std;

int multiply(vector<bool> fan, vector<bool> group, int fan_num, int group_num)
{
             int count =0;
             vector<bool> res(fan_num+group_num, false);
             
             for(int i= 0;i<fan_num;i++)
                     for(int j=0;j<group_num;j++)
                     {   
                         if(!res[i+j]){
                                      res[i+j] = (fan[i]&group[j]);           
                         }    
                     }
             
             for(int i = group_num-1; i<fan_num;i++)
             {
                     if(!res[i]) count++;
             }
             return count;
}

int main(int argc, char *argv[])
{
    string group_str, fan_str;
    group_str = "MFMFMFFFMMMFMFMFMFMFFFMMMFMFMFMFMFFFMMMFMFMFMFMFFFMMMFMFMFMFMFFFMMMFMFMFMFMFFFMMMFMFMFMFMFFFMMMFMF";
    fan_str = "MMFFFFFMFFFMFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFvFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFFMMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFF";
    //group_str = "MFMFMFFFMMMFMF";
   // fan_str = "MMFFFFFMFFFMFFFFFFMFFFMFFFFMFMMFFFFFFF";
    clock_t begin = clock();
   
    int group_num = group_str.size();
    int fan_num = fan_str.size();
    
    vector<bool> group(group_num, false), fan(fan_num, false);
    
    for(int i =0; i<group_num;i++)
    {
            group[i] = (group_str[i] == 'M');
           // printf(group[i] ? "T" : "F");
    }
   // printf("\n");
    for(int i =0; i<fan_num;i++)
    {
            fan[fan_num - i -1] = (fan_str[i] == 'M');
          //  printf(fan[fan_num - i -1] ? "T" : "F");
    }
    
    int count = multiply(fan, group,fan_num, group_num);
    printf("\ncount :%d\n",count);
    
    clock_t end = clock();
    double time_spent = (double)(end - begin) / CLOCKS_PER_SEC;
    printf("time_spent : %f\n",time_spent);
   system("PAUSE");
   return EXIT_SUCCESS;
}
